[server]
  debug_trace = false

[bluemix]
  iam_url = "https://iam.bluemix.net"
  iam_client_id = "bx"
  iam_client_secret = "bx"
  iam_api_key = "iam_api_key"
  refresh_token = ""
  containers_api_route = "https://eu-gb.containers.cloud.ibm.com"
  containers_api_route_private = "https://eu-gb.containers.cloud.ibm.com"
  containers_api_csrf_token = "containers_api_csrf_token"

[softlayer]
  softlayer_block_enabled = false
  softlayer_block_provider_name = "SOFTLAYER-BLOCK"
  softlayer_file_enabled = false
  softlayer_file_provider_name = "SOFTLAYER-FILE"
  softlayer_username = ""
  softlayer_api_key = ""
  softlayer_endpoint_url = "https://api.softlayer.com/rest/v3"
  softlayer_iam_endpoint_url = "https://api.softlayer.com/mobile/v3"
  softlayer_datacenter = "mex01"
  softlayer_api_timeout = "30s"
  softlayer_vol_provision_timeout = "30m"
  softlayer_api_retry_interval = "5s"

[vpc]
  vpc_enabled = true
  provider_type = "gc"
  vpc_provider_type = "vpc-block"
  gc_token_exchange_endpoint_url = "https://iam.bluemix.net"
  gc_riaas_endpoint_url = "https://eu-gb.iaas.cloud.ibm.com"
  gc_riaas_endpoint_private_url = "https://eu-gb.iaas.cloud.ibm.com"
  gc_resource_group_id = "gc_resource_group_id"
  gc_api_key = "gc_api_key"

  encryption = false
  iks_token_exchange_endpoint_private_url = "https://eu-gb.containers.cloud.ibm.com"
  max_retry_attempt  = 2 # 10 times with exponential re-try with max gap max_retry_gap
  max_retry_gap =  60 # 2 minutes
  api_version = "2019-07-02"
  vpc_api_generation = 1
  vpc_api_timeout = "120s"

[IKS]
  iks_enabled = false
  iks_block_provider_name = "iks-vpc-classic"
